[package]
name = "store"
version.workspace = true
edition.workspace = true

[dependencies]
protocol = { path = "../protocol" }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
thiserror = { workspace = true }
chrono = { workspace = true }
dirs = "6"
tempfile = "3"
